package com.hmvsoluciones.saas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CitaAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertCitaAllPropertiesEquals(Cita expected, Cita actual) {
    assertCitaAutoGeneratedPropertiesEquals(expected, actual);
    assertCitaAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertCitaAllUpdatablePropertiesEquals(Cita expected, Cita actual) {
    assertCitaUpdatableFieldsEquals(expected, actual);
    assertCitaUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertCitaAutoGeneratedPropertiesEquals(Cita expected, Cita actual) {
    assertThat(actual)
      .as("Verify Cita auto generated properties")
      .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertCitaUpdatableFieldsEquals(Cita expected, Cita actual) {
    assertThat(actual)
      .as("Verify Cita relevant properties")
      .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
      .satisfies(a -> assertThat(a.getHoraInicio()).as("check horaInicio").isEqualTo(expected.getHoraInicio()))
      .satisfies(a -> assertThat(a.getDuracionMinutos()).as("check duracionMinutos").isEqualTo(expected.getDuracionMinutos()))
      .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
      .satisfies(a -> assertThat(a.getEsUrgente()).as("check esUrgente").isEqualTo(expected.getEsUrgente()))
      .satisfies(a -> assertThat(a.getEstadoCita()).as("check estadoCita").isEqualTo(expected.getEstadoCita()));
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertCitaUpdatableRelationshipsEquals(Cita expected, Cita actual) {
    assertThat(actual)
      .as("Verify Cita relationships")
      .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()))
      .satisfies(a -> assertThat(a.getEmpleado()).as("check empleado").isEqualTo(expected.getEmpleado()));
  }
}
