package com.hmvsoluciones.saas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NegocioAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertNegocioAllPropertiesEquals(Negocio expected, Negocio actual) {
    assertNegocioAutoGeneratedPropertiesEquals(expected, actual);
    assertNegocioAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertNegocioAllUpdatablePropertiesEquals(Negocio expected, Negocio actual) {
    assertNegocioUpdatableFieldsEquals(expected, actual);
    assertNegocioUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertNegocioAutoGeneratedPropertiesEquals(Negocio expected, Negocio actual) {
    assertThat(actual)
      .as("Verify Negocio auto generated properties")
      .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertNegocioUpdatableFieldsEquals(Negocio expected, Negocio actual) {
    assertThat(actual)
      .as("Verify Negocio relevant properties")
      .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
      .satisfies(a -> assertThat(a.getResponsable()).as("check responsable").isEqualTo(expected.getResponsable()))
      .satisfies(a -> assertThat(a.getCelular()).as("check celular").isEqualTo(expected.getCelular()))
      .satisfies(a -> assertThat(a.getCorreo()).as("check correo").isEqualTo(expected.getCorreo()))
      .satisfies(a -> assertThat(a.getSubscriptionKey()).as("check subscriptionKey").isEqualTo(expected.getSubscriptionKey()))
      .satisfies(a -> assertThat(a.getEsActivo()).as("check esActivo").isEqualTo(expected.getEsActivo()));
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertNegocioUpdatableRelationshipsEquals(Negocio expected, Negocio actual) {
    // empty method
  }
}
