package com.hmvsoluciones.saas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TemplateAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertTemplateAllPropertiesEquals(Template expected, Template actual) {
    assertTemplateAutoGeneratedPropertiesEquals(expected, actual);
    assertTemplateAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertTemplateAllUpdatablePropertiesEquals(Template expected, Template actual) {
    assertTemplateUpdatableFieldsEquals(expected, actual);
    assertTemplateUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertTemplateAutoGeneratedPropertiesEquals(Template expected, Template actual) {
    assertThat(actual)
      .as("Verify Template auto generated properties")
      .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertTemplateUpdatableFieldsEquals(Template expected, Template actual) {
    assertThat(actual)
      .as("Verify Template relevant properties")
      .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
      .satisfies(a -> assertThat(a.getContenido()).as("check contenido").isEqualTo(expected.getContenido()))
      .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertTemplateUpdatableRelationshipsEquals(Template expected, Template actual) {
    // empty method
  }
}
