export enum EstadoCita {
  PROGRAMADA = 'PROGRAMADA',

  CONFIRMADA = 'CONFIRMADA',

  EN_PROCESO = 'EN_PROCESO',

  TERMINADA = 'TERMINADA',

  CANCELADA = 'CANCELADA',

  NO_LLEGO = 'NO_LLEGO',

  IMPREVISTO = 'IMPREVISTO',
}
